## 1.3 Cleaning and Data Preparation

In this phase we check for null values, duplicates, or structural anomalies to delete it and improve the dataset of `person_voice_works`, `profiles`, `recommendations` and `stats`.

---

### Loading Data from csv files

In [1]:
from lib.dbconnection import create_db_engine
from lib import readSaveCsv as rsc
import pandas as pd

engine = create_db_engine()

person_voice_works = rsc.import_data(engine, "person_voice_works")
profiles = rsc.import_data(engine, "profiles")
recommendations = rsc.import_data(engine, "recommendations")
stats = rsc.import_data(engine, "stats")

Successo: Dati letti correttamente.
Successo: Dati letti correttamente.
Successo: Dati letti correttamente.
Successo: Dati letti correttamente.

---

### Checking DataFrames info and visualise first rows

In [2]:
person_voice_works.info()
print('\n')
profiles.info()
print('\n')
recommendations.info()
print('\n')
stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 488565 entries, 0 to 488564
Data columns (total 5 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   person_mal_id     488565 non-null  int64
 1   role              488565 non-null  object
 2   anime_mal_id      488565 non-null  int64
 3   character_mal_id  488565 non-null  int64
 4   language          488565 non-null  object
dtypes: int64(3), object(2)
memory usage: 18.6+ MB


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79299 entries, 0 to 79298
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   username       79299 non-null  object
 1   gender         79299 non-null  object
 2   birthday       79299 non-null  object
 3   location       79299 non-null  object
 4   joined         79299 non-null  object
 5   watching       79297 non-null  object
 6   completed      79297 non-null  object
 7   on_hold        79297 non-null  object
 8   dropped        79297 non-null  object
 9   plan_to_watch  79297 non-null  object
 10  birthday_dt    79299 non-null  datetime64[ns]
 11  birth_year     79299 non-null  int64
 12  age            79299 non-null  int64
dtypes: datetime64[ns](1), int64(2), object(10)
memory usage: 7.9+ MB


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105249 entries, 0 to 105248
Data columns (total 2 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   mal_id                 105249 non-null  int64
 1   recommendation_mal_id  105249 non-null  object
dtypes: int64(1), object(1)
memory usage: 1.6+ MB


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28955 entries, 0 to 28954
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   mal_id               28955 non-null  int64
 1   watching             28955 non-null  int64
 2   completed            28955 non-null  int64
 3   on_hold              28955 non-null  int64
 4   dropped              28955 non-null  int64
 5   plan_to_watch        28955 non-null  int64
 6   total                28955 non-null  int64
 7   score_1_votes        28525 non-null  float64
 8   score_1_percentage   28525 non-null  float64
 9   score_2_votes        28525 non-null  float64
 10  score_2_percentage   28525 non-null  float64
 11  score_3_votes        28525 non-null  float64
 12  score_3_percentage   28525 non-null  float64
 13  score_4_votes        28525 non-null  float64
 14  score_4_percentage   28525 non-null  float64
 15  score_5_votes        28525 non-null  float64
 16  score_5_percentage   28525 non-null  float64
 17  score_6_votes        28525 non-null  float64
 18  score_6_percentage   28525 non-null  float64
 19  score_7_votes        28525 non-null  float64
 20  score_7_percentage   28525 non-null  float64
 21  score_8_votes        28525 non-null  float64
 22  score_8_percentage   28525 non-null  float64
 23  score_9_votes        28525 non-null  float64
 24  score_9_percentage   28525 non-null  float64
 25  score_10_votes       28525 non-null  float64
 26  score_10_percentage  28525 non-null  float64
dtypes: float64(20), int64(7)
memory usage: 6.0 MB

In [3]:
person_voice_works

        person_mal_id        role  anime_mal_id  character_mal_id  language
0                   1        Main         55830              2514  Japanese
1                   1  Supporting         60602              2822  Japanese
2                   1  Supporting         59229            140499  Japanese
3                   1  Supporting         60427            275856  Japanese
4                   1  Supporting         62067            190335  Japanese
...               ...         ...           ...               ...       ...
488560          89839  Supporting         40111            274622  Mandarin
488561          89840  Supporting         60544            266412  Mandarin
488562          89841  Supporting         60544            266416  Mandarin
488563          89842  Supporting         36896            279922  Japanese
488564          89952  Supporting         60260            279778  Japanese

[488565 rows x 5 columns]

In [4]:
profiles

,username,gender,birthday,location,joined,watching,completed,on_hold,dropped,plan_to_watch,birthday_dt,birth_year,age
0,RinsAl,Male,"Jul 7, 1989",Japan,"Oct 19, 2009",16,484,5,19,70,1989-07-07,1989,36
1,ishimori,Female,"Apr 17, 2000",France,"Dec 7, 2018",1,91,16,14,30,2000-04-17,2000,25
2,Rins_,Male,"Jul 15, 1988",Japan,"Jun 6, 2013",5,110,0,1,46,1988-07-15,1988,37
3,FollowValen,Male,"Jul 8, 1996",Spain,"Oct 7, 2018",9,48,9,5,33,1996-07-08,1996,29
4,ishiruchan,Female,"Jun 16, 2003",China,"Aug 26, 2018",0,108,9,5,87,2003-06-16,2003,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...
79294,arisuri,Female,"Apr 15, 2001",Thailand,"Nov 6, 2019",4,122,23,0,35,2001-04-15,2001,24
79295,arisux,Female,"Aug 21, 1998",United Kingdom,"Feb 5, 2014",8,309,43,36,142,1998-08-21,1998,27
79296,arisvgawa,Female,"Mar 3, 2001",Japan,"Oct 2, 2024",1,16,0,0,0,2001-03-03,2001,24
79297,ariu82,Male,"Sep 17, 2003",China,"Dec 25, 2020",1,228,15,12,29,2003-09-17,2003,22
79298,arizima23,Female,"Jun 23, 1998",Spain,"Mar 15, 2019",15,64,0,4,4,1998-06-23,1998,27

In [5]:
recommendations

        mal_id recommendation_mal_id
0         3269                   317
1         3269                  6922
2         3269                   299
3         3269                  3446
4         3269                  5681
...        ...                   ...
105244   31245                  1689
105245   31245                 35434
105246   31245                 31798
105247   31245                 21995
105248   36305                 42897

[105249 rows x 2 columns]

In [6]:
stats

,mal_id,watching,completed,on_hold,dropped,plan_to_watch,total,score_1_votes,score_1_percentage,score_2_votes,...,score_6_votes,score_6_percentage,score_7_votes,score_7_percentage,score_8_votes,score_8_percentage,score_9_votes,score_9_percentage,score_10_votes,score_10_percentage
0,59356,7,146,4,20,20,197,2.0,2.2,0.0,...,33.0,36.3,19.0,20.9,2.0,2.2,0.0,0.0,1.0,1.1
1,56036,21,770,8,29,113,941,5.0,1.0,6.0,...,138.0,27.4,144.0,28.6,81.0,16.1,17.0,3.4,40.0,8.0
2,2928,451,14953,302,349,6472,22527,101.0,1.0,93.0,...,2054.0,21.1,2709.0,27.8,1500.0,15.4,875.0,9.0,608.0,6.2
3,3269,726,22790,452,537,9762,34267,120.0,0.8,156.0,...,2457.0,16.0,4157.0,27.0,3075.0,20.0,1919.0,12.5,1400.0,9.1
4,4469,241,6918,182,266,3528,11135,83.0,1.9,104.0,...,888.0,20.6,871.0,20.2,592.0,13.7,308.0,7.1,315.0,7.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28950,59421,11349,17353,574,1440,15729,46445,54.0,0.3,40.0,...,2303.0,14.5,5545.0,34.9,3919.0,24.7,1598.0,10.1,1235.0,7.8
28951,31245,10332,140676,2989,1416,94249,249662,357.0,0.3,484.0,...,15972.0,15.3,34370.0,33.0,24387.0,23.4,10480.0,10.1,7589.0,7.3
28952,36305,928,16119,388,243,9656,27334,48.0,0.5,28.0,...,1839.0,18.3,3258.0,32.5,2009.0,20.0,887.0,8.8,936.0,9.3
28953,34895,896,2387,375,356,1512,5526,116.0,6.1,80.0,...,437.0,23.2,280.0,14.8,170.0,9.0,68.0,3.6,125.0,6.6
28954,56606,4,83,2,15,20,124,3.0,5.2,1.0,...,15.0,25.9,7.0,12.1,1.0,1.7,0.0,0.0,4.0,6.9

### `null` values detection and removal

In [7]:
profiles = profiles.dropna(subset=['username'])

### Duplicate rows detection and removal

In [8]:
print(f"Number of rows duplicated (person_voice_works): {person_voice_works.duplicated().sum()}\\n")
print(f"Number of rows duplicated (profiles): {profiles.duplicated().sum()}\\n")
print(f"Number of rows duplicated (recommendations): {recommendations.duplicated().sum()}\\n")
print(f"Number of rows duplicated (stats): {stats.duplicated().sum()}")

Number of rows duplicated (person_voice_works): 0\n
Number of rows duplicated (profiles): 0\n
Number of rows duplicated (recommendations): 0\n
Number of rows duplicated (stats): 0

In [9]:
person_voice_works = person_voice_works.drop_duplicates(keep="first")
profiles = profiles.drop_duplicates(keep="first")
recommendations = recommendations.drop_duplicates(keep="first")
stats = stats.drop_duplicates(keep="first")

profiles['birthday_dt'] = pd.to_datetime(profiles['birthday'], errors='coerce')

profiles['birth_year'] = profiles['birthday_dt'].dt.year
profiles['age'] = 2025 - profiles['birth_year']

profiles = profiles.dropna(subset=['age', 'gender'])
profiles = profiles[profiles['gender'] != '']

print(f"Profili validi pronti per l'analisi: {len(profiles)}")
print(profiles[['username', 'age', 'gender']].head())

Profili validi pronti per l'analisi: 79299
      username  age  gender
0       RinsAl   36    Male
1     ishimori   25  Female
2        Rins_   37    Male
3  FollowValen   29    Male
4   ishiruchan   22  Female

In [10]:
print(f"Number of rows duplicated (person_voice_works): {person_voice_works.duplicated().sum()}\\n")
print(f"Number of rows duplicated (profiles): {profiles.duplicated().sum()}\\n")
print(f"Number of rows duplicated (recommendations): {recommendations.duplicated().sum()}\\n")
print(f"Number of rows duplicated (stats): {stats.duplicated().sum()}")

Number of rows duplicated (person_voice_works): 0\n
Number of rows duplicated (profiles): 0\n
Number of rows duplicated (recommendations): 0\n
Number of rows duplicated (stats): 0

### Typo correction

In [11]:
person_voice_works = person_voice_works.copy()
recommendations = recommendations.copy()

person_voice_works.loc[:, 'role'] = person_voice_works['role'].astype('category')

### Saving in cleaned csv files

In [12]:
rsc.save_data(person_voice_works, 'person_voice_works', engine)
rsc.save_data(profiles, 'profiles', engine)
rsc.save_data(recommendations, 'recommendations', engine)
rsc.save_data(stats, 'stats', engine)

Successo: 488565 righe caricate nella tabella 'person_voice_works'.
Successo: 79299 righe caricate nella tabella 'profiles'.
Successo: 105249 righe caricate nella tabella 'recommendations'.
Successo: 28955 righe caricate nella tabella 'stats'.